/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/forecast/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Forecast
         * @description "Try again" on the not-assessable screen: asks the forecast source whether it answers now.
         */
        post: operations["retry_forecast_api_forecast_retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Route
         * @description Route between two searched places over the official trail network.
         */
        post: operations["create_route_api_routes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Places
         * @description Place-name search, for picking the ends of a route.
         */
        get: operations["search_places_api_routes_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/{route_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Route */
        get: operations["get_route_api_routes__route_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/{route_id}/assessment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Route Assessment
         * @description Hazards for the hike on `date` (default: today in Switzerland), evaluated client-side at arrival.
         */
        get: operations["get_route_assessment_api_routes__route_id__assessment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/{route_id}/narration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Route Narration
         * @description The assessment's hazards phrased in `lang`, with the guidance each is grounded in.
         *
         *     Separate from the assessment so a slow model never holds it up. Never fails on the model's
         *     account: a hazard without a `body` keeps its templated copy.
         */
        get: operations["get_route_narration_api_routes__route_id__narration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AltRoute
         * @description The same route cut short: turn back at `stop_id` instead of going on over the crux.
         */
        AltRoute: {
            /** Duration */
            duration: string;
            /**
             * Grade
             * @enum {string}
             */
            grade: "T1" | "T2" | "T3" | "T4" | "T5" | "T6";
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "altRoute";
            /** Place */
            place: string;
            /** Stopid */
            stopId: string;
        };
        /** AssessmentData */
        AssessmentData: {
            /** Alternatives */
            alternatives: (components["schemas"]["StartEarlier"] | components["schemas"]["AltRoute"])[];
            /** Conditions */
            conditions: {
                [key: string]: components["schemas"]["StopConditions"][];
            };
            forecast: components["schemas"]["Forecast"];
            /** Gaps */
            gaps: ("warnings" | "snowline" | "pace")[];
            /** Hazards */
            hazards: components["schemas"]["HazardDef"][];
            /** Notevaluated */
            notEvaluated: components["schemas"]["NotEvaluated"][];
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "assessed" | "partial" | "not_assessable";
            /** Stale */
            stale: boolean;
        };
        /**
         * Citation
         * @description A guidance passage a hazard is grounded in: `guidance/corpus/<id>.md`, and the page it paraphrases.
         */
        Citation: {
            /** Id */
            id: string;
            /** Publisher */
            publisher: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** Forecast */
        Forecast: {
            /** Checkedat */
            checkedAt: number;
            /** Issuedat */
            issuedAt: number;
            /** Model */
            model: string;
            /** Stalehours */
            staleHours: number;
            /** Unavailablereason */
            unavailableReason?: ("source" | "beyond_horizon") | null;
            /** Unavailablesince */
            unavailableSince: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HazardDef */
        HazardDef: {
            facts?: components["schemas"]["HazardFacts"] | null;
            /** Hasliftsif */
            hasLiftsIf: boolean;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "gusts" | "showers" | "thunder" | "cold" | "snow" | "visibility" | "daylight";
            /** Place */
            place?: string | null;
            /** Provenance */
            provenance: string;
            /** Stops */
            stops: {
                [key: string]: components["schemas"]["SeverityInterval"][];
            };
            window: components["schemas"]["Window"];
        };
        /**
         * HazardFacts
         * @description The figures behind a hazard, at the stop where it is worst, for the copy to quote.
         *
         *     Numbers reach the hazard text only through here: the strings carry placeholders, never figures.
         *     Every field is optional. A hazard raised by a warning alone has no facts at all, and the copy
         *     then falls back to a sentence that needs none.
         */
        HazardFacts: {
            /** Cloudbasem */
            cloudBaseM?: number | null;
            /** Elevationm */
            elevationM?: number | null;
            /** Feelslikec */
            feelsLikeC?: number | null;
            /** Freezinglevelm */
            freezingLevelM?: number | null;
            /** Gustkmh */
            gustKmh?: number | null;
            /** Precipmm */
            precipMm?: number | null;
            /** Snowlinem */
            snowlineM?: number | null;
            /** Sunset */
            sunset?: number | null;
            /** Thresholdkmh */
            thresholdKmh?: number | null;
            /** Thresholdmm */
            thresholdMm?: number | null;
            /** Thunderpct */
            thunderPct?: number | null;
        };
        /** KeyLabel */
        KeyLabel: {
            /**
             * Key
             * @enum {string}
             */
            key: "stop.lake" | "stop.moraine" | "stop.descent";
        };
        /**
         * Leg
         * @description A mapped section of the official route.
         */
        Leg: {
            /** Ascentm */
            ascentM?: number | null;
            /** Cables */
            cables?: boolean | null;
            /** Distancekm */
            distanceKm?: number | null;
            /** Fromindex */
            fromIndex?: number | null;
            /** Fromstop */
            fromStop: string;
            /**
             * Grade
             * @enum {string}
             */
            grade: "T1" | "T2" | "T3" | "T4" | "T5" | "T6";
            /** Gradeestimated */
            gradeEstimated?: boolean | null;
            /** Id */
            id: string;
            /** Stopids */
            stopIds: string[];
            /** Toindex */
            toIndex?: number | null;
            /** Tostop */
            toStop: string;
        };
        /**
         * NarratedHazard
         * @description The phrased explanation of one hazard, and what grounds it.
         *
         *     `body` carries the same placeholders as the hazard copy (`{gust}`, `{place}`, …) and never a
         *     figure: the client fills them from `HazardDef.facts`, so every number shown is the engine's.
         *     Absent when narration is off, failed, or broke a copy rule; the client then shows its template.
         */
        NarratedHazard: {
            /** Body */
            body?: string | null;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Id */
            id: string;
        };
        /** Narration */
        Narration: {
            /** Enabled */
            enabled: boolean;
            /** Hazards */
            hazards: components["schemas"]["NarratedHazard"][];
            /** Model */
            model?: string | null;
        };
        /** NotEvaluated */
        NotEvaluated: {
            /** Legids */
            legIds: string[];
        };
        /** PlaceLabel */
        PlaceLabel: {
            /** Place */
            place: string;
        };
        /**
         * PlaceRef
         * @description A place the hiker picked out of search, as it comes back in.
         */
        PlaceRef: {
            /** Latlng */
            latLng: [
                number,
                number
            ];
            /** Name */
            name: string;
        };
        /**
         * PlaceResult
         * @description One search result. `rank` is swisstopo's own ordering; lower sorts first.
         *
         *     Named apart from `domain.PlaceHit` on purpose: that one is the parsed source object and must
         *     never reach the wire, and `test_openapi_contract` checks by name that it does not.
         */
        PlaceResult: {
            /** Latlng */
            latLng: [
                number,
                number
            ];
            /** Name */
            name: string;
            /** Rank */
            rank: number;
        };
        /** RetryResult */
        RetryResult: {
            /** Available */
            available: boolean;
            /** Checkedat */
            checkedAt: number;
        };
        /** Route */
        Route: {
            /** Ascentm */
            ascentM: number;
            /** Bailoutname */
            bailoutName: string;
            /** Bailoutstopid */
            bailoutStopId?: string | null;
            /** Cruxstopid */
            cruxStopId: string;
            /** Descentm */
            descentM?: number | null;
            /** Distancekm */
            distanceKm: number;
            /** Elevations */
            elevations?: number[] | null;
            /** Fromname */
            fromName: string;
            /** Geometry */
            geometry?: [
                number,
                number
            ][] | null;
            /**
             * Grade
             * @enum {string}
             */
            grade: "T1" | "T2" | "T3" | "T4" | "T5" | "T6";
            /** Id */
            id: string;
            /** Lastboat */
            lastBoat: number;
            /** Legs */
            legs: components["schemas"]["Leg"][];
            /** Stops */
            stops: components["schemas"]["Stop"][];
            /** Toname */
            toName: string;
            /** Turnarounddefault */
            turnaroundDefault: number;
            /** Waypoints */
            waypoints: components["schemas"]["Waypoint"][];
        };
        /** RouteRequest */
        RouteRequest: {
            from: components["schemas"]["PlaceRef"];
            to: components["schemas"]["PlaceRef"];
            /** Via */
            via?: components["schemas"]["PlaceRef"][];
        };
        /**
         * SeverityInterval
         * @description A severity that holds from `from` up to, but not including, `to`.
         */
        SeverityInterval: {
            /** From */
            from: number;
            /**
             * Severity
             * @enum {string}
             */
            severity: "none" | "mod" | "high";
            /** To */
            to: number;
        };
        /** StartEarlier */
        StartEarlier: {
            /** Dependson */
            dependsOn: string;
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "startEarlier";
            /** Start */
            start: number;
        };
        /**
         * Stop
         * @description A point on the day's timeline, in walking order (out and back).
         */
        Stop: {
            /** Breakminutes */
            breakMinutes?: number | null;
            /** Id */
            id: string;
            /** Label */
            label: components["schemas"]["PlaceLabel"] | components["schemas"]["KeyLabel"];
            /** Legminutes */
            legMinutes: number;
            /** Waypointid */
            waypointId: string;
        };
        /**
         * StopConditions
         * @description What the forecast says at a stop over `[from, to)`: the numbers the crux card shows.
         */
        StopConditions: {
            /** Feelslikec */
            feelsLikeC?: number | null;
            /** From */
            from: number;
            /** Gustkmh */
            gustKmh?: number | null;
            /** Precipmm */
            precipMm?: number | null;
            /** To */
            to: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Waypoint */
        Waypoint: {
            /** Elevationm */
            elevationM: number;
            /** Id */
            id: string;
            /** Latlng */
            latLng: [
                number,
                number
            ];
            /** Name */
            name: string;
        };
        /** Window */
        Window: {
            /** From */
            from: number;
            /** To */
            to: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    retry_forecast_api_forecast_retry_post: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_route_api_routes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_places_api_routes_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_route_api_routes__route_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                route_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_route_assessment_api_routes__route_id__assessment_get: {
        parameters: {
            query?: {
                scenario?: "assessed" | "partial" | "not_assessable" | "stale";
                date?: string | null;
            };
            header?: never;
            path: {
                route_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_route_narration_api_routes__route_id__narration_get: {
        parameters: {
            query?: {
                scenario?: "assessed" | "partial" | "not_assessable" | "stale";
                date?: string | null;
                lang?: "en" | "fr";
            };
            header?: never;
            path: {
                route_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Narration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
