/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/forecast/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Forecast
         * @description "Try again" on the not-assessable screen: the source is still down.
         */
        post: operations["retry_forecast_api_forecast_retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recent-routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recent Routes */
        get: operations["get_recent_routes_api_recent_routes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Route
         * @description Route between two searched places over the official trail network.
         */
        post: operations["create_route_api_routes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Places
         * @description Place-name search, for picking the ends of a route.
         */
        get: operations["search_places_api_routes_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/{route_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Route */
        get: operations["get_route_api_routes__route_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/{route_id}/assessment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Route Assessment */
        get: operations["get_route_assessment_api_routes__route_id__assessment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AltRoute */
        AltRoute: {
            /** Duration */
            duration: string;
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "altRoute";
        };
        /** AssessmentData */
        AssessmentData: {
            /** Alternatives */
            alternatives: (components["schemas"]["StartEarlier"] | components["schemas"]["AltRoute"])[];
            forecast: components["schemas"]["Forecast"];
            /** Gaps */
            gaps: ("warnings" | "snowline" | "pace")[];
            /** Hazards */
            hazards: components["schemas"]["HazardDef"][];
            /** Notevaluated */
            notEvaluated: components["schemas"]["NotEvaluated"][];
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "assessed" | "partial" | "not_assessable";
            /** Stale */
            stale: boolean;
        };
        /** FieldPosition */
        FieldPosition: {
            /** Elapsed */
            elapsed: number;
            /** Nextascentm */
            nextAscentM: number;
            /** Nextkm */
            nextKm: number;
            /** Remainingtocrux */
            remainingToCrux: number;
        };
        /** Forecast */
        Forecast: {
            /** Checkedat */
            checkedAt: number;
            /** Feelslikec */
            feelsLikeC: number;
            /** Issuedat */
            issuedAt: number;
            /** Model */
            model: string;
            /** Stalehours */
            staleHours: number;
            /** Unavailablesince */
            unavailableSince: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HazardDef */
        HazardDef: {
            /** Buildupfrom */
            buildUpFrom?: number | null;
            /** Hasliftsif */
            hasLiftsIf: boolean;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "gusts" | "showers";
            /** Place */
            place?: string | null;
            /** Provenance */
            provenance: string;
            /** Stops */
            stops: {
                [key: string]: "none" | "mod" | "high";
            };
            window: components["schemas"]["Window"];
        };
        /** KeyLabel */
        KeyLabel: {
            /**
             * Key
             * @enum {string}
             */
            key: "stop.lake" | "stop.moraine" | "stop.descent";
        };
        /**
         * Leg
         * @description A mapped section of the official route.
         */
        Leg: {
            /** Ascentm */
            ascentM?: number | null;
            /** Cables */
            cables?: boolean | null;
            /** Distancekm */
            distanceKm?: number | null;
            /** Fromindex */
            fromIndex?: number | null;
            /** Fromstop */
            fromStop: string;
            /**
             * Grade
             * @enum {string}
             */
            grade: "T1" | "T2" | "T3" | "T4" | "T5" | "T6";
            /** Gradeestimated */
            gradeEstimated?: boolean | null;
            /** Id */
            id: string;
            /** Stopids */
            stopIds: string[];
            /** Toindex */
            toIndex?: number | null;
            /** Tostop */
            toStop: string;
        };
        /** NotEvaluated */
        NotEvaluated: {
            /** Legids */
            legIds: string[];
        };
        /** PlaceLabel */
        PlaceLabel: {
            /** Place */
            place: string;
        };
        /**
         * PlaceRef
         * @description A place the hiker picked out of search, as it comes back in.
         */
        PlaceRef: {
            /** Latlng */
            latLng: [
                number,
                number
            ];
            /** Name */
            name: string;
        };
        /**
         * PlaceResult
         * @description One search result. `rank` is swisstopo's own ordering; lower sorts first.
         *
         *     Named apart from `domain.PlaceHit` on purpose: that one is the parsed source object and must
         *     never reach the wire, and `test_openapi_contract` checks by name that it does not.
         */
        PlaceResult: {
            /** Latlng */
            latLng: [
                number,
                number
            ];
            /** Name */
            name: string;
            /** Rank */
            rank: number;
        };
        /** RecentRoute */
        RecentRoute: {
            /** Checkedon */
            checkedOn: string;
            /**
             * Grade
             * @enum {string}
             */
            grade: "T1" | "T2" | "T3" | "T4" | "T5" | "T6";
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** RetryResult */
        RetryResult: {
            /** Available */
            available: boolean;
            /** Checkedat */
            checkedAt: number;
        };
        /** Route */
        Route: {
            /** Ascentm */
            ascentM: number;
            /** Bailoutname */
            bailoutName: string;
            /** Bailoutstopid */
            bailoutStopId?: string | null;
            /** Cruxstopid */
            cruxStopId: string;
            /** Descentm */
            descentM?: number | null;
            /** Distancekm */
            distanceKm: number;
            /** Elevations */
            elevations?: number[] | null;
            field: components["schemas"]["FieldPosition"];
            /** Fromname */
            fromName: string;
            /** Geometry */
            geometry?: [
                number,
                number
            ][] | null;
            /**
             * Grade
             * @enum {string}
             */
            grade: "T1" | "T2" | "T3" | "T4" | "T5" | "T6";
            /** Id */
            id: string;
            /** Lastboat */
            lastBoat: number;
            /** Legs */
            legs: components["schemas"]["Leg"][];
            /** Stops */
            stops: components["schemas"]["Stop"][];
            /** Toname */
            toName: string;
            /** Turnarounddefault */
            turnaroundDefault: number;
            /** Waypoints */
            waypoints: components["schemas"]["Waypoint"][];
        };
        /** RouteRequest */
        RouteRequest: {
            from: components["schemas"]["PlaceRef"];
            to: components["schemas"]["PlaceRef"];
            /** Via */
            via?: components["schemas"]["PlaceRef"][];
        };
        /** StartEarlier */
        StartEarlier: {
            /** Dependson */
            dependsOn: string;
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "startEarlier";
            /** Start */
            start: number;
        };
        /**
         * Stop
         * @description A point on the day's timeline, in walking order (out and back).
         */
        Stop: {
            /** Breakminutes */
            breakMinutes?: number | null;
            /** Id */
            id: string;
            /** Label */
            label: components["schemas"]["PlaceLabel"] | components["schemas"]["KeyLabel"];
            /** Legminutes */
            legMinutes: number;
            /** Waypointid */
            waypointId: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Waypoint */
        Waypoint: {
            /** Elevationm */
            elevationM: number;
            /** Id */
            id: string;
            /** Latlng */
            latLng: [
                number,
                number
            ];
            /** Name */
            name: string;
        };
        /** Window */
        Window: {
            /** From */
            from: number;
            /** To */
            to: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    retry_forecast_api_forecast_retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetryResult"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_recent_routes_api_recent_routes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentRoute"][];
                };
            };
        };
    };
    create_route_api_routes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_places_api_routes_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_route_api_routes__route_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                route_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_route_assessment_api_routes__route_id__assessment_get: {
        parameters: {
            query?: {
                scenario?: "assessed" | "partial" | "not_assessable" | "stale";
            };
            header?: never;
            path: {
                route_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
